language: java

sudo: false
dist: trusty

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install: ./gradlew -version

script:
  - java -version
  - ./gradlew -version
  - ./gradlew check
