language: java

sudo: false
dist: trusty

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install:
- ./gradlew -version

script:
- java -version
- ./gradlew -version
- export GRADLE_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED -Dorg.gradle.daemon=false"
# - export GRADLE_OPTS="--permit-illegal-access"
- ./gradlew --debug --stacktrace check
